//src/app/layout.tsx
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "../redux/provider";
import HeaderComponent from "./component/header/HeaderComponent";
import Footer from "./component/footer/Footer";
import { Metadata } from "next";
import ModalWrap from "./component/modal/ModalWrap";
import ReactQueryProvider from "@/utill/ReactQueryProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <Providers>
            <ModalWrap />
            <HeaderComponent />
            {children}
            <Footer />
          </Providers>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
