//src/app/layout.tsx
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "../redux/provider";
import HeaderItme from "@/model/header";
import HeaderComponent from "./component/header/HeaderComponent";
import { useMemo } from "react";
import Footer from "./component/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("레이아웃");

  const DUMMY_DATA: HeaderItme[] = useMemo(() => {
    return [
      { title: "HOME", id: 0, url: "/" },
      { title: "SHOP", id: 1, url: "/shop/" },
      {
        title: "게시판",
        id: 2,
        url: "/notice/",
      },
    ];
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <HeaderComponent data={DUMMY_DATA} />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
