//src/app/layout.tsx
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "../redux/provider";
import HeaderComponent from "./component/header/HeaderComponent";
import Footer from "./component/footer/Footer";
import { HeadType } from "@/model/head";
const inter = Inter({ subsets: ["latin"] });
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <HeaderComponent />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
