name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
      - run: npm run export
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
      - run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # 배포될 브랜치
          FOLDER: out # 이 폴더에 있는 파일을 배포
          CLEAN: true # 배포 브랜치에 있는 파일들을 자동으로 삭제
1
name: Build and Deploy
2
on:
3
  push:
4
    branches:
5
      - master
6
​
7
jobs:
8
  build-and-deploy:
9
    runs-on: ubuntu-latest
10
    steps:
11
      - name: Checkout
12
        uses: actions/checkout@v2.3.1
13
        with:
14
          persist-credentials: false
15
​
16
      - name: Install and Build
17
        uses: actions/setup-node@v1
18
      - run: npm install
19
      - run: npm run build
20
      - run: npm run export
21
        env:
22
          CI: true
23
          DEPLOY_TARGET: gh-pages
24
      - run: touch out/.nojekyll
25
​
26
      - name: Deploy
27
        uses: JamesIves/github-pages-deploy-action@3.7.1
28
        with:
29
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
30
          BRANCH: gh-pages  # 배포될 브랜치
31
          FOLDER: out # 이 폴더에 있는 파일을 배포
32
          CLEAN: true # 배포 브랜치에 있는 파일들을 자동으로 삭제
